### ISSUE TITLE
Deleting last mip for 2:1 aspect ratio

### ISSUE THREAD

**Issue by z929669** [Ethatron/ddsopt#2]
SKYRIM: For the following, mid-distant trees are stripped of varying amounts of edge foliage due to the automatic deletion of the highest mipmap level by DDSopt. Deletion occurs I assume since the aspect ratio of these texture images is not 1:1 (11 mipmap levels expected for 1024x1024 AND 2048x1024). 12th mip for 2048x1024, fe. is omitted in processing, and there does not seem to be a way to prevent this behavior.

Request a feature be added to selectively control that behavior. (not certain which other 2:1 ratio textures are adversely affected):
# treepineforestbranchcomp.dds

... \textures\landscape\trees\treepineforestbranchcomp.dds
processing:
 Format           : DXT3
 Dimensions       : 2048x1024 - 12 to 11 levels

**Comment by Ethatron** [comment]
I'll add the option ASAP.

**Comment by Ethatron** [comment]
I added the option, but it has nothing to do with the problem you encountered.

**Comment by z929669** [comment]
Thanks, I understand the alpha transparency issue now. Thanks for adding the option anyway though  ...and presumably moving the menu option --> Ethatron said: 

"In the menu-entry "Behave->Textures->Compress all known file-types" you can turn off compression of "non-DDS -> DDS" files. It's a bad position, so I'll move the menu-entry to the "Ignore" menu for the next update."

Will the updated version be posted soon or still more updates coming?

**Comment by Ethatron** [comment]
Soon, I changed a lot and now I have to check all permutations of setting if they still work. The new version probably has some 2-3x speedup over the old, and you have all the funky "delta" images of before<->after. You also get a special contrast-filter for the foilage, so you may not exactly get that extreme result as the vanilla pine, but's pretty good, I expect it'll look better and you'll be able to use it on the aspen as well. :^P

**Comment by z929669** [comment]
Wow, thanks! Anxious to check this feature out (and see how it applies to the aspen). I left another post for you on the DDSopt STEP-forum thread related to this: 
http://forum.step-project.com/showthread.php?tid=228&pid=5566#pid5566
