### ISSUE TITLE
Contrast-adjustment for alpha-maps

### ISSUE THREAD

**Issue by Ethatron** [Ethatron/ddsopt#6]
- raises contrast every mip-level
- as with gamma-correction, it's in the filter kernel and only applies to level >0

**Comment by Ethatron** [comment]
- implemented, needs to be tested

**Comment by z929669** [comment]
Ready to test if I know just what to look for ;)

I have used this new feature, but notice no difference in-game as yet, so it would be helpful to know where to look.

**Comment by Ethatron** [comment]
Well, I implemented it so you do NOT have a difference to the original maps. Without it they look thinned out.
